server:
  servlet:
    context-path: /corporative
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.17:5432/ecua3d
    username: postgres
    password: homeassistant
  jpa:
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.100.17:8080/realms/ecua3d
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

token:
  converter:
    principal-attribute: preferred_username
    resource-id: demo-app